### ISSUE TITLE
k8s llama2 Data_preparation error inquiry

### ISSUE THREAD

**Issue by donggyulee1** [NVIDIA/NeMo-Megatron-Launcher#236]
### hi
I am setting up K8s with the following settings, referring to the part below.
Reference: https://docs.nvidia.com/nemo-framework/user-guide/latest/playbooks/kubernetes.html

ubuntu 22.04
KubeFlow Training Operator: 1.6.0
MPI Operator: 0.4.0
Kubernetes: 1.27.4
A100*40G 2EA
NFS

Data_preparation is in progress with llama2, and Data preparation complete appears in nlp-data-prep-launcher, but only these files exist in the folder and the .bin and .idx files are not visible. Even with gpt3, the symptoms are the same.
need your help!!

![2](https://github.com/NVIDIA/NeMo-Megatron-Launcher/assets/45442982/d2ed3dcd-8971-4438-b3d1-3c5a4c3edb0e)

# download_llama_pile.yaml settings
![5](https://github.com/NVIDIA/NeMo-Megatron-Launcher/assets/45442982/791280c9-1030-483e-a11a-06e5ddcc6355)

---
# default/nlp-data-prep-launcher-b282j error screen
![3](https://github.com/NVIDIA/NeMo-Megatron-Launcher/assets/45442982/14d6f110-10ba-472b-a555-084fdbef539a)
![1](https://github.com/NVIDIA/NeMo-Megatron-Launcher/assets/45442982/d6eb8944-e868-454b-b1fc-25d8734c848a)

**Comment by Syulin7** [comment]
@donggyulee1 I have the same issue, have you solved it yet?
