### ISSUE TITLE
Is there a contribution guide for this repo?

### ISSUE THREAD

**Issue by kaiyux** [NVIDIA/NeMo-Megatron-Launcher#7]
I might need to add some deployment code to this repo, better to read contribution guides before that.

Besides, looks like we don't have code style requirements for this repo. I can add pre-commit tooltrain to automatically format the Python code if you feel like it's needed. : )

**Comment by yaoyu-33** [comment]
Hi @kaiyux that would be great. Feel free to add style requirements. We did try to fit into nemo style but there might be some misses here and there. Thanks!

**Comment by kaiyux** [comment]
I've file a PR: https://github.com/NVIDIA/NeMo-Megatron-Launcher/pull/9, please review it at your convenience and let me know if there're any problems. Thanks!

**Comment by kaiyux** [comment]
Merged, closing.
